function observation = encodeCoverageObservation(logged)
%ENCODECOVERAGEOBSERVATION RL durum yapısını [0,1] vektörüne çevirir.

rows = logged.Scenario.rows;
cols = logged.Scenario.cols;
headingOneHot = zeros(4,1);
headingOneHot(logged.Heading) = 1;

observation = double([ ...
    logged.CutMask(:); ...
    logged.Scenario.obstacleMask(:); ...
    (logged.Cell(1)-1)/max(1,rows-1); ...
    (logged.Cell(2)-1)/max(1,cols-1); ...
    headingOneHot; ...
    logged.CoverageRatio]);
end
